/*
 * Autor.java
 *
 * Generated with Matisse Schema Definition Language 9.1.9
 * Generation date: Thu Feb 09 09:15:01 2017
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package biblioteca;

import com.matisse.reflect.*;

/**
 * <code>Autor</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Autor extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.9
     * Generation Date: Thu Feb 09 09:15:01 2017
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Autor</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("biblioteca.Autor"));

    /**
     * Gets the <code>Autor</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Autor(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Autor(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Autor.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Autor.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Autor.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Autor.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'nombre' */

    /** Attribute <code>nombre</code> cache ID */
    private static int nombreCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre",CID));

    /**
     * Gets the <code>nombre</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreCID);
    }


    /**
     * Gets the <code>nombre</code> attribute value.
     * @return the value
     *
     * @see #setNombre
     * @see #removeNombre
     */
    public final String getNombre() {
        return getString(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombre</code> attribute value.
     * @param val the new value
     *
     * @see #getNombre
     * @see #removeNombre
     */
    public final void setNombre(String val) {
        setString(getNombreAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombre</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final void removeNombre() {
        removeValue(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreNull() {
        return isNull(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreDefaultValue() {
        return isDefaultValue(getNombreAttribute(getMtDatabase()));
    }


    /* Attribute 'apellidos' */

    /** Attribute <code>apellidos</code> cache ID */
    private static int apellidosCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("apellidos",CID));

    /**
     * Gets the <code>apellidos</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getApellidosAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(apellidosCID);
    }


    /**
     * Gets the <code>apellidos</code> attribute value.
     * @return the value
     *
     * @see #setApellidos
     * @see #removeApellidos
     */
    public final String getApellidos() {
        return getString(getApellidosAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>apellidos</code> attribute value.
     * @param val the new value
     *
     * @see #getApellidos
     * @see #removeApellidos
     */
    public final void setApellidos(String val) {
        setString(getApellidosAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>apellidos</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getApellidos
     * @see #setApellidos
     */
    public final void removeApellidos() {
        removeValue(getApellidosAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getApellidos
     * @see #setApellidos
     */
    public final boolean isApellidosNull() {
        return isNull(getApellidosAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getApellidos
     * @see #setApellidos
     */
    public final boolean isApellidosDefaultValue() {
        return isDefaultValue(getApellidosAttribute(getMtDatabase()));
    }


    /* Attribute 'edad' */

    /** Attribute <code>edad</code> cache ID */
    private static int edadCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("edad",CID));

    /**
     * Gets the <code>edad</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getEdadAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(edadCID);
    }


    /**
     * Gets the <code>edad</code> attribute value.
     * @return the value
     *
     * @see #setEdad
     * @see #removeEdad
     */
    public final String getEdad() {
        return getString(getEdadAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>edad</code> attribute value.
     * @param val the new value
     *
     * @see #getEdad
     * @see #removeEdad
     */
    public final void setEdad(String val) {
        setString(getEdadAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>edad</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getEdad
     * @see #setEdad
     */
    public final void removeEdad() {
        removeValue(getEdadAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getEdad
     * @see #setEdad
     */
    public final boolean isEdadNull() {
        return isNull(getEdadAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getEdad
     * @see #setEdad
     */
    public final boolean isEdadDefaultValue() {
        return isDefaultValue(getEdadAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'escribe' */

    /** Relationship <code>escribe</code> cache ID */
    private static int escribeCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("escribe",CID));

    /**
     * Gets the <code>escribe</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getEscribeRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(escribeCID);
    }

    /**
     * Gets the <code>escribe</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getEscribeSize
     * @see #escribeIterator
     * @see #setEscribe
     * @see #removeEscribe
     */
    public final biblioteca.Obra[] getEscribe() {
        return (biblioteca.Obra[])getSuccessors(getEscribeRelationship(getMtDatabase()), biblioteca.Obra.class);
    }

    /**
     * Counts the <code>escribe</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getEscribe
     * @see #escribeIterator
     * @see #setEscribe
     * @see #removeEscribe
     */
    public final int getEscribeSize() {
        return getSuccessorSize(getEscribeRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>escribe</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getEscribe
     * @see #getEscribeSize
     * @see #setEscribe
     * @see #removeEscribe
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> escribeIterator() {
        return this.<E>successorIterator(getEscribeRelationship(getMtDatabase()), biblioteca.Obra.class);
    }

    /**
     * Sets the <code>escribe</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getEscribe
     * @see #getEscribeSize
     * @see #escribeIterator
     * @see #removeEscribe
     */
    public final void setEscribe(biblioteca.Obra[] succs) {
        setSuccessors(getEscribeRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>escribe</code> successors list.
     * @param succ the object to add
     *
     * @see #getEscribe
     * @see #getEscribeSize
     * @see #escribeIterator
     * @see #setEscribe
     * @see #removeEscribe
     */
    public final void prependEscribe(biblioteca.Obra succ) {
        prependSuccessor(getEscribeRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>escribe</code> successors list.
     * @param succ the object to add
     *
     * @see #getEscribe
     * @see #setEscribe
     * @see #removeEscribe
     * @see #getEscribeSize
     * @see #escribeIterator
     */
    public final void appendEscribe(biblioteca.Obra succ) {
        appendSuccessor(getEscribeRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>escribe</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getEscribe
     * @see #setEscribe
     * @see #removeEscribe
     * @see #getEscribeSize
     * @see #escribeIterator
     */
    public final void appendEscribe(biblioteca.Obra[] succs) {
        addSuccessors(getEscribeRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>escribe</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getEscribe
     * @see #setEscribe
     * @see #getEscribeSize
     * @see #escribeIterator
     */
    public void removeEscribe(biblioteca.Obra[] succs) {
        removeSuccessors(getEscribeRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>escribe</code> successors list.
     * @param succ the object to remove
     *
     * @see #getEscribe
     * @see #setEscribe
     * @see #getEscribeSize
     * @see #escribeIterator
     */
    public void removeEscribe(biblioteca.Obra succ) {
        removeSuccessor(getEscribeRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>escribe</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearEscribe() {
        clearSuccessors(getEscribeRelationship(getMtDatabase()));
    }


    /*
     * SQL Method access methods
     */

    /**
     * SQL Method call.
     * @return the SQL Method return value
     */
    public String dameNombreyApellidos()
        throws java.sql.SQLException {
        return (String)executeSQLMethod("biblioteca.Autor", "dameNombreyApellidos", 0,
                                        new Object[0],
                                        new int[0],
                                        new int[0]);
    }

    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Autor(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Autor]";
    }
}
